languageCode: de-de
baseurl: //malumdiscordi.ae/genesis
title: Genesis

publishdir: public

theme: novel

permalinks:
  chapter: /kapitel/:slug/
  page: /meta/:slug/

params:
  Description: >
    Der Anfang.

    Roman in kleinen Kapiteln mit unregelmäßigen Updates.
    Verfasst durch Johanna Appel.

  Email: malumdiscordiae@mailbox.org
  TwitterUsername: ephe_meral
  GitHubUsername: ephe-meral
